- name: Copy redis repo file
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Install redis Server and Shell
  ansible.builtin.yum:
    name: redis
    state: present

- name: Check if redis.cnf exists
  ansible.builtin.stat:
    path: /etc/redis/redis.cnf
  register: redis_cnf

- name: Update redis.cnf if exists
  ansible.builtin.replace:
    path: /etc/redis/redis.cnf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  when: redis_cnf.stat.exists


- name: Restart redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes

