- name: Copy redis repo file
  ansible.builtin.copy:
    src: redis.repo
    dest: /etc/yum.repos.d/redis.repo

- name: Install redis Server and Shell
  ansible.builtin.yum:
    name: redis
    state: present

- name: Update redis Listen Address
  ansible.builtin.replace:
    path: "{{item}}"
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
  loop:
    - /etc/redis.conf
    - /etc/redis/redis.cnf

- name: Restart redis
  ansible.builtin.systemd:
    name: redis
    state: restarted
    enabled: yes

