- name: Copy MongoDB repo file
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: Install MongoDB Server
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Install MongoDB Shell (mongosh)
  ansible.builtin.yum:
    name: mongodb-mongosh
    state: installed

- name: Update MongoDB Listen Address
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restart MongoDB
  ansible.builtin.systemd:
    name: mongod
    state: restarted
    enabled: yes

- name: Unarchive a file that is already on the remote machine
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes

# ✅ Unarchive the MongoDB schema files (only once, no need to repeat)
- name: Download and extract MongoDB schema files
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/mongodb/archive/main.zip
    dest: /tmp
    remote_src: yes

# ✅ Load the schema using the correct path
- name: Load MongoDB schema files
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{ item }}.js"
    idempotent: yes
  loop:
    - catalogue
    - users
