- name: Copy MySQL repo file
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo
    owner: root
    group: root
    mode: '0644'

- name: Disable default MySQL module
  ansible.builtin.command: dnf module disable mysql -y

- name: Clean DNF metadata
  ansible.builtin.command: dnf clean all


- name: Install MySQL Server and Python 3 client
  ansible.builtin.yum:
    name:
      - mysql-community-server
      - python3   # replaces deprecated MySQL-python
    state: present

- name: Enable and start MySQL service
  ansible.builtin.systemd:
    name: mysqld
    state: started
    enabled: true



- name: Check Root Default Password
  block:
    - name: Get MySQL version to check the DB Connection
      mysql_info:
        login_user: root
        login_password: "{{MYSQL_PASSWORD}}"
        filter: version
  rescue:
    - name: Load MYSQL Log File
      ansible.builtin.slurp:
        src: /var/log/mysqld.log
      register: mysql_log

    - name: Declare Facts
      ansible.builtin.set_fact:
        DEFAULT_PASS: "{{mysql_log['content'] | b64decode | regex_findall('.*temporary password.*') | join(' ') |split(' ') | last }}"

    - name: Change MySQL
      ansible.builtin.shell: echo "ALTER USER 'root'@'localhost' IDENTIFIED BY '{{MYSQL_PASSWORD}}';" | mysql --connect-expired-password -uroot -p"{{DEFAULT_PASS}}"

- name: Check Validate plugin exists
  ansible.builtin.shell: echo "uninstall plugin validate_password;" | mysql -uroot -p{{MYSQL_PASSWORD}}
  ignore_errors: yes

- name: Download MySQL Schema files
  ansible.builtin.unarchive:
    src: "https://github.com/roboshop-devops-project/mysql/archive/main.zip"
    dest: /tmp
    remote_src: yes

- name: Load Schema
  community.mysql.mysql_db:
    state: import
    name: all
    target: /tmp/mysql-main/shipping.sql
    login_user: root
    login_password: "{{MYSQL_PASSWORD}}"