- name: SetUp NodeJS repos
  ansible.builtin.shell: curl --silent --location https://rpm.nodesource.com/setup_16.x | bash

- name: Install NodeJs
  ansible.builtin.yum:
    name: nodejs
    state: installed

- name: Add roboshop user
  ansible.builtin.user:
    name: roboshop
    comment: Roboshop App User

- name: Remove old app content
  ansible.builtin.file:
    path: /home/roboshop/{{COMPONENT}}
    state: absent

- name: Download {{COMPONENT}} zip
  ansible.builtin.get_url:
    url: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp/{{COMPONENT}}.zip

- name: Extract {{COMPONENT}} content
  ansible.builtin.unarchive:
    src: /tmp/{{COMPONENT}}.zip
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes
    owner: roboshop
    group: roboshop
    extra_opts: [--strip-components=1]

- name: Install nodejs dependencies
  community.general.npm:
    path: /home/roboshop/{{COMPONENT}}
  become: yes
  become_user: roboshop

- name: Setup {{COMPONENT}} systemd service
  ansible.builtin.template:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service
    mode: 0644

- name: Reload systemd daemon and restart {{COMPONENT}}
  ansible.builtin.systemd:
    name: "{{COMPONENT}}"
    state: restarted
    enabled: yes
    daemon_reload: yes
